name: Publish beta to docker registry

on:
  push:
    branches:
      - main

jobs:

  release:
    strategy:
      matrix:
        go_version: [1.16]
        os: [ubuntu-latest]

    if: github.repository == 'PasteUs/PasteMeGoBackend'
    name: Build with go ${{ matrix.go_version }} on ${{ matrix.os }} and upload
    runs-on: ${{ matrix.os }}

    steps:

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Login to Aliyun Docker Registry
#        uses: docker/login-action@v1
#        with:
#          registry: registry.cn-hangzhou.aliyuncs.com
#          username: ${{ secrets.ALIYUN_DOCKER_REGISTRY_USERNAME }}
#          password: ${{ secrets.ALIYUN_DOCKER_REGISTRY_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
            linux/386
          push: true
          tags: |
            pasteme/go-backend:beta
#            registry.cn-hangzhou.aliyuncs.com/pasteus/pasteme-go-backend:beta

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Trigger Webhook
        run: |
          curl -X POST "${{ secrets.BETA_WEBHOOK }}backend"
